### ISSUE TITLE
Portainer Stack/Docker compose not working at all

### ISSUE THREAD

**Issue by NovaViper** [romancin/rclonebrowser-docker#33]
Hey, im trying to use this image but whenever I run the container stack, I get this error

```
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
```

And nothing else, this is my compose file
```
---
version: "2.1"
services:
  rclonebrowser:
    image: romancin/rclonebrowser:latest
    container_name: rclonebrowser
    network_mode: host
    ports:
      - 5800:5800
    environment:
      - TZ=America/Chicago
    volumes:
      - /DockerStuff/Config/RCloneBrowser:/config
      - /srv/dev-disk-by-uuid-8e405f50-f017-4a04-81c0-cf5c94033afc/NCDatabase:/nextcloud
    restart: unless-stopped
```

Im running OpenMediaVault v5.6.21-2 with Docker v5:20.10.12~3-0~debian-buster and Portainer 2.11.0. The machine I'm running the OMV instance on is a Raspberry Pi 4B+ with a 64bit version of Raspbian lite
